const BOARD_SIZE_FACTOR = 0.75
const BUTTON_SIZE = 40
const BUTTON_PADDING = 5
const GRID_SIZE = 6
const BUTTON_STEP = BUTTON_PADDING + BUTTON_SIZE
const GRID_SPACE = 100

const NEXT_GRID_START = GRID_SPACE+GRID_SIZE*BUTTON_STEP

const INITIAL_X = 50
const INITIAL_Y = 200